# Generated by Django 4.0 on 2022-03-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_options_remove_post_mazmuni_post_daromadi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('daromadi', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Davlatlar',
            },
        ),
    ]
