# Generated by Django 4.0 on 2022-03-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BoxChart',
                'verbose_name_plural': 'Box Chartlar',
            },
        ),
    ]
