# Generated by Django 4.0 on 2022-03-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boxchart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxchart',
            old_name='open',
            new_name='opens',
        ),
    ]
